### ISSUE TITLE
Ag-Grid Angular 2 CSS is not working 

### ISSUE THREAD

**Issue by upardhi** [ag-grid/ag-grid-angular#238]
Hi

I tried 3 different way but still, I am not able to use the CSS

First:
@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-balham.css";

Second:
Put all content available in above file in my component

Third:
@import url('../node_modules/ag-grid/dist/styles/ag-grid.css');
@import url('../node_modules/ag-grid/dist/styles/ag-theme-fresh.css');

Still, CSS is not working

![image](https://user-images.githubusercontent.com/6356988/45942353-b0e28100-bfff-11e8-9321-7551945a587c.png)

Angular Version: 6.0.0

Ag-Grid Example: https://www.ag-grid.com/angular-getting-started/

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-angular version:** 2.0.X

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by changhuixu** [comment]
Do you have a sample repo?

**Comment by zach-luman** [comment]
I am experiencing same issue.
I am using Angular7.

**Comment by RaminduSamarawickrama** [comment]
Hi @upardhi , You have to put `@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-balham.css";` to the style.css in your project directory(not in component's css), otherwise it wont work. Had the same issue, fixed by this

**Comment by jaywantn** [comment]
I applied these changes but still not working. I tried to put root style.css file but still the same issue
